services:
  - type: web
    name: toll-dashboard-system-1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Toll_Dashboard_Code.py
    autoDeployTrigger: commit
